name: Move Changed Files

on:
  push:
    branches:
      - main  # Change this to your branch name if different

jobs:
  move_files_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
        
      # Using tj-actions/changed-files@v42 to get changed files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'  # Change to the Python version you are using

      - name: Execute Python script
        run: |
          python script.py
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.CHANGED_FILES }}
