name: Move Changed Files

on:
  push:
    branches:
      - main  # Change this to your branch name if different

jobs:
  move_files_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get list of changed files
        id: changed-files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})" >> $GITHUB_ENV

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'  # Change to the Python version you are using

      - name: Execute Python script
        run: |
          python script.py
